{% set name = "dash_cytoscape" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a71ad4fe095570b71d4ad7c0d29199e9780c2e6796173d3b25fccc2cc58c855f

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - dash
    - python >=3.5

test:
  imports:
    - dash_cytoscape

about:
  home: https://github.com/plotly/dash-cytoscape
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Component Library for Dash aimed at facilitating network visualization in Python, wrapped around Cytoscape.js
  doc_url: https://dash.plot.ly/cytoscape
  dev_url: https://github.com/plotly/dash-cytoscape

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - adbeda
